version: '3.5'
services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=supremerobot
    networks:
      - integration
  redis:
    image: redis:6
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - integration

networks:
  integration:
    name: ${NETWORK_NAME}