package models

import "errors"

var (
	errInvalidExpire      = errors.New("invalid expire")
	errInvalidIP          = errors.New("invalid ip")
	errInvalidHost        = errors.New("invalid host")
	errInvalidMBox        = errors.New("invalid mbox")
	errInvalidName        = errors.New("invalid name")
	errInvalidNS          = errors.New("invalid ns")
	errInvalidPort        = errors.New("invalid port")
	errInvalidPriority    = errors.New("invalid priority")
	errInvalidRefresh     = errors.New("invalid refresh")
	errInvalidRetry       = errors.New("invalid retry")
	errInvalidTTL         = errors.New("invalid ttl")
	errInvalidWeight      = errors.New("invalid weight")
	errLengthExceededText = errors.New("text length exceeded")
	errMissingExpire      = errors.New("expire must be defined")
	errMissingIP          = errors.New("ip must be defined")
	errMissingHost        = errors.New("host must be defined")
	errMissingMBox        = errors.New("mbox must be defined")
	errMissingName        = errors.New("name must be defined")
	errMissingNS          = errors.New("ns must be defined")
	errMissingPort        = errors.New("port must be defined")
	errMissingPriority    = errors.New("priority must be defined")
	errMissingRefresh     = errors.New("refresh must be defined")
	errMissingRetry       = errors.New("retry must be defined")
	errMissingText        = errors.New("text must be defined")
	errMissingTTL         = errors.New("ttl must be defined")
	errMissingType        = errors.New("type must be defined")
	errMissingWeight      = errors.New("weight must be defined")
	errUnknownType        = errors.New("unknown type")
)
